# This is a notebook for finding/producing compilation errors in AMRs

See https://github.com/ciemss/pyciemss/pull/545

In [1]:
import os
import pyciemss

In [2]:
MODEL_PATH = "../../docs/source/"

model1 = os.path.join(MODEL_PATH, "sir-working.json")
model2 = os.path.join(MODEL_PATH, "sir-undef-var-initial.json")
model3 = os.path.join(MODEL_PATH, "sir-undef-var-obs.json")
model4 = os.path.join(MODEL_PATH, "sir-undef-var-rate-law.json")

model5 = os.path.join(MODEL_PATH, "regnet-model.json")
model6 = os.path.join(MODEL_PATH, "seird-petrinet.json")

model7 = "https://raw.githubusercontent.com/DARPA-ASKEM/simulation-integration/main/data/models/LV_rabbits_wolves_model02_regnet.json"

In [3]:
start_time = 0.0
end_time = 100.0
logging_step_size = 10.0
num_samples = 10

In [4]:
result1 = pyciemss.sample(model1, end_time, logging_step_size, num_samples, start_time=start_time)
display(result1['data'].head())

,timepoint_id,sample_id,timepoint_unknown,persistent_p_cbeta_param,persistent_p_tr_param,I_state,R_state,S_state
0,0,0,10.0,0.404726,16.915386,30.432138,5.145192,965.422363
1,1,0,20.0,0.404726,16.915386,413.403564,107.194817,480.401825
2,2,0,30.0,0.404726,16.915386,521.950012,424.029022,55.020782
3,3,0,40.0,0.404726,16.915386,319.522675,671.339172,10.138031
4,4,0,50.0,0.404726,16.915386,181.366486,815.860352,3.773030

In [5]:
result1 = pyciemss.sample(model3, end_time, logging_step_size, num_samples, start_time=start_time)
display(result1['data'].head())

,timepoint_id,sample_id,timepoint_unknown,persistent_p_cbeta_param,persistent_p_tr_param,I_state,R_state,S_state
0,0,0,10.0,0.314315,16.947807,12.629418,2.715014,985.655701
1,1,0,20.0,0.314315,16.947807,132.071030,33.872257,835.056580
2,2,0,30.0,0.314315,16.947807,466.631622,213.751877,320.616638
3,3,0,40.0,0.314315,16.947807,433.224640,496.613251,71.162109
4,4,0,50.0,0.314315,16.947807,273.430481,703.961792,23.606506

In [6]:
# Regnet
result1 = pyciemss.sample(model5, end_time, logging_step_size, num_samples, start_time=start_time)
display(result1['data'].head())

,timepoint_id,sample_id,timepoint_unknown,persistent_alpha_param,persistent_gamma_param,persistent_beta_param,persistent_delta_param,persistent_G0_param,persistent_C0_param,Chupacabra_state,Goats_state
0,0,0,10.0,0.953527,0.210243,0.203525,0.45596,47.912212,6.538258,16.043890,3.332153e-33
1,1,0,20.0,0.953527,0.210243,0.203525,0.45596,47.912212,6.538258,1.959914,5.544283e-35
2,2,0,30.0,0.953527,0.210243,0.203525,0.45596,47.912212,6.538258,0.239422,1.450959e-31
3,3,0,40.0,0.953527,0.210243,0.203525,0.45596,47.912212,6.538258,0.029248,1.638509e-27
4,4,0,50.0,0.953527,0.210243,0.203525,0.45596,47.912212,6.538258,0.003573,2.212128e-23

In [7]:
# Petrinet
result1 = pyciemss.sample(model6, end_time, logging_step_size, num_samples, start_time=start_time)
display(result1['data'].head())

,timepoint_id,sample_id,timepoint_unknown,persistent_beta_param,persistent_death_param,persistent_gamma_param,persistent_I0_param,D_state,E_state,I_state,R_state,S_state,infected_observable_state,dead_observable_state
0,0,0,10.0,0.394703,0.004497,0.488629,1.668417,0.245372,20.139961,11.040165,54.317051,19339956.0,11.040165,0.245372
1,1,0,20.0,0.394703,0.004497,0.488629,1.668417,0.451905,14.429527,7.922418,100.036339,19339916.0,7.922418,0.451905
2,2,0,30.0,0.394703,0.004497,0.488629,1.668417,0.599979,10.343465,5.679016,132.814926,19339894.0,5.679016,0.599979
3,3,0,40.0,0.394703,0.004497,0.488629,1.668417,0.706123,7.414461,4.070866,156.311584,19339872.0,4.070866,0.706123
4,4,0,50.0,0.394703,0.004497,0.488629,1.668417,0.782210,5.314867,2.918097,173.154556,19339854.0,2.918097,0.782210

In [8]:
result1 = pyciemss.sample(model7, end_time, logging_step_size, num_samples, start_time=start_time)
display(result1['data'].head())

,timepoint_id,sample_id,timepoint_unknown,persistent_alpha_param,persistent_gamma_param,persistent_beta_param,persistent_delta_param,persistent_R0_param,persistent_W0_param,Rabbits_state,Wolves_state
0,0,0,10.0,1.297674,2.94464,0.943995,1.054984,9.324169,6.632075,10.761606,0.136714
1,1,0,20.0,1.297674,2.94464,0.943995,1.054984,9.324169,6.632075,6.519197,0.012377
2,2,0,30.0,1.297674,2.94464,0.943995,1.054984,9.324169,6.632075,3.893156,0.004689
3,3,0,40.0,1.297674,2.94464,0.943995,1.054984,9.324169,6.632075,2.322278,0.004221
4,4,0,50.0,1.297674,2.94464,0.943995,1.054984,9.324169,6.632075,1.385680,0.006372

In [10]:
# Load petrinet as template model
from mira.sources.amr import model_from_url, model_from_json_file
seird_petri_model = model_from_json_file(model6)
type(seird_petri_model)

mira.metamodel.template_model.TemplateModel

In [11]:
seird_petri_model.observables

{'infected': Observable(name='infected', display_name='infected', description=None, identifiers={}, context={}, units=None, expression=I),
 'dead': Observable(name='dead', display_name='dead', description=None, identifiers={}, context={}, units=None, expression=D)}

In [12]:
# template_model_to_regnet_json
from mira.modeling.amr.regnet import template_model_to_regnet_json
regnet_version = template_model_to_regnet_json(seird_petri_model)

In [13]:
import json
with open("seird-regnet.json", "w") as regnet_json:
    json.dump(regnet_version, regnet_json, indent=1)

In [15]:
model8 = os.path.join(MODEL_PATH, "seird-regnet.json")
seird_regnet_model = model_from_json_file(model8)
seird_regnet_model.initials

{'S': Initial(concept=Concept(name='S', display_name=None, description=None, identifiers={'ido': '0000514'}, context={}, units=None), expression=-I0 + total_population),
 'I': Initial(concept=Concept(name='I', display_name=None, description=None, identifiers={'ido': '0000511'}, context={}, units=None), expression=I0),
 'E': Initial(concept=Concept(name='E', display_name=None, description=None, identifiers={'apollosv': '0000154'}, context={}, units=None), expression=40.0),
 'R': Initial(concept=Concept(name='R', display_name=None, description=None, identifiers={'ido': '0000592'}, context={}, units=None), expression=0.0),
 'D': Initial(concept=Concept(name='D', display_name=None, description=None, identifiers={'ncit': 'C28554'}, context={}, units=None), expression=0.0)}

In [16]:
result1 = pyciemss.sample(model8, end_time, logging_step_size, num_samples, start_time=start_time)
display(result1['data'].head())

ERROR:root:
                ###############################

                There was an exception in pyciemss

                Error occured in function: sample

                Function docs :
    Load a model from a file, compile it into a probabilistic program, and sample from it.

    Args:
        model_path_or_json: Union[str, Dict]
            - A path to a AMR model file or JSON containing a model in AMR form.
        end_time: float
            - The end time of the sampled simulation.
        logging_step_size: float
            - The step size to use for logging the trajectory.
        num_samples: int
            - The number of samples to draw from the model.
        solver_method: str
            - The method to use for solving the ODE. See torchdiffeq's `odeint` method for more details.
            - If performance is incredibly slow, we suggest using `euler` to debug.
              If using `euler` results in faster simulation, the issue is likely that the model is stiff.
        solver_options: Dict[str, Any]
            - Options to pass to the solver. See torchdiffeq' `odeint` method for more details.
        start_time: float
            - The start time of the model. This is used to align the `start_state` from the
              AMR model with the simulation timepoints.
            - By default we set the `start_time` to be 0.
        inferred_parameters: Optional[pyro.nn.PyroModule]
            - A Pyro module that contains the inferred parameters of the model.
              This is typically the result of `calibrate`.
            - If not provided, we will use the default values from the AMR model.
        static_state_interventions: Dict[float, Dict[str, Intervention]]
            - A dictionary of static interventions to apply to the model.
            - Each key is the time at which the intervention is applied.
            - Each value is a dictionary of the form {state_variable_name: intervention_assignment}.
            - Note that the `intervention_assignment` can be any type supported by
              :func:`~chirho.interventional.ops.intervene`, including functions.
        static_parameter_interventions: Dict[float, Dict[str, Intervention]]
            - A dictionary of static interventions to apply to the model.
            - Each key is the time at which the intervention is applied.
            - Each value is a dictionary of the form {parameter_name: intervention_assignment}.
            - Note that the `intervention_assignment` can be any type supported by
              :func:`~chirho.interventional.ops.intervene`, including functions.
        dynamic_state_interventions: Dict[
                                        Callable[[torch.Tensor, Dict[str, torch.Tensor]], torch.Tensor],
                                        Dict[str, Intervention]
                                        ]
            - A dictionary of dynamic interventions to apply to the model.
            - Each key is a function that takes in the current state of the model and returns a tensor.
              When this function crosses 0, the dynamic intervention is applied.
            - Each value is a dictionary of the form {state_variable_name: intervention_assignment}.
            - Note that the `intervention_assignment` can be any type supported by
              :func:`~chirho.interventional.ops.intervene`, including functions.
        dynamic_parameter_interventions: Dict[
                                            Callable[[torch.Tensor, Dict[str, torch.Tensor]], torch.Tensor],
                                            Dict[str, Intervention]
                                            ]
            - A dictionary of dynamic interventions to apply to the model.
            - Each key is a function that takes in the current state of the model and returns a tensor.
              When this function crosses 0, the dynamic intervention is applied.
            - Each value is a dictionary of the form {parameter_name: intervention_assignment}.
            - Note that the `intervention_assignment` can be any type supported by
              :func:`~chirho.interventional.ops.intervene`, including functions.
        alpha: float
            - Risk level for alpha-superquantile outputs in the results dictionary.

    Returns:
        result: Dict[str, torch.Tensor]
            - Dictionary of outputs with following attributes:
                - data: The samples from the model as a pandas DataFrame.
                - unprocessed_result: Dictionary of outputs from the model.
                    - Each key is the name of a parameter or state variable in the model.
                    - Each value is a tensor of shape (num_samples, num_timepoints) for state variables
                    and (num_samples,) for parameters.
                - quantiles: The quantiles for ensemble score calculation as a pandas DataFrames.
                - risk: Dictionary with each key as the name of a state with
                a dictionary of risk estimates for each state at the final timepoint.
                    - risk: alpha-superquantile risk estimate
                    Superquantiles can be intuitively thought of as a tail expectation, or an average
                    over a portion of worst-case outcomes. Given a distribution of a
                    quantity of interest (QoI), the superquantile at level \alpha\in[0, 1] is
                    the expected value of the largest 100(1 -\alpha)% realizations of the QoI.
                    - qoi: Samples of quantity of interest (value of the state at the final timepoint)
                - schema: Visualization. (If visual_options is truthy)


                ################################

Traceback (most recent call last):
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/pyro/poutine/trace_messenger.py", line 174, in __call__
    ret = self.fn(*args, **kwargs)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
  File "/Users/altu809/Projects/pyciemss/pyciemss/interfaces.py", line 305, in wrapped_model
    full_trajectory = model(
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/pyro/nn/module.py", line 449, in __call__
    result = super().__call__(*args, **kwargs)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/altu809/Projects/pyciemss/pyciemss/compiled_dynamics.py", line 77, in forward
    simulate(self.deriv, self.initial_state(), start_time, end_time)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/pyro/nn/module.py", line 686, in cached_fn
    return fn(self, *args, **kwargs)
  File "/Users/altu809/Projects/pyciemss/pyciemss/compiled_dynamics.py", line 48, in initial_state
    return eval_initial_state(self.src, self)
  File "/Users/altu809/anaconda3/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Users/altu809/Projects/pyciemss/pyciemss/mira_integration/compiled_dynamics.py", line 144, in _eval_initial_state_mira
    numeric_initial_state = param_module.numeric_initial_state_func(**parameters)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/sympytorch/sympy_module.py", line 266, in forward
    return torch.stack(out, dim=-1)
RuntimeError: stack expects a non-empty TensorList

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/altu809/Projects/pyciemss/pyciemss/integration_utils/custom_decorators.py", line 10, in wrapped
    result = function(*args, **kwargs)
  File "/Users/altu809/Projects/pyciemss/pyciemss/interfaces.py", line 332, in sample
    samples = pyro.infer.Predictive(
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/pyro/infer/predictive.py", line 273, in forward
    return _predictive(
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/pyro/infer/predictive.py", line 78, in _predictive
    max_plate_nesting = _guess_max_plate_nesting(model, model_args, model_kwargs)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/pyro/infer/predictive.py", line 21, in _guess_max_plate_nesting
    model_trace = poutine.trace(model).get_trace(*args, **kwargs)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/pyro/poutine/trace_messenger.py", line 198, in get_trace
    self(*args, **kwargs)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/pyro/poutine/trace_messenger.py", line 180, in __call__
    raise exc from e
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/pyro/poutine/trace_messenger.py", line 174, in __call__
    ret = self.fn(*args, **kwargs)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
  File "/Users/altu809/Projects/pyciemss/pyciemss/interfaces.py", line 305, in wrapped_model
    full_trajectory = model(
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/pyro/nn/module.py", line 449, in __call__
    result = super().__call__(*args, **kwargs)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/altu809/Projects/pyciemss/pyciemss/compiled_dynamics.py", line 77, in forward
    simulate(self.deriv, self.initial_state(), start_time, end_time)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/pyro/nn/module.py", line 686, in cached_fn
    return fn(self, *args, **kwargs)
  File "/Users/altu809/Projects/pyciemss/pyciemss/compiled_dynamics.py", line 48, in initial_state
    return eval_initial_state(self.src, self)
  File "/Users/altu809/anaconda3/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Users/altu809/Projects/pyciemss/pyciemss/mira_integration/compiled_dynamics.py", line 144, in _eval_initial_state_mira
    numeric_initial_state = param_module.numeric_initial_state_func(**parameters)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/sympytorch/sympy_module.py", line 266, in forward
    return torch.stack(out, dim=-1)
RuntimeError: stack expects a non-empty TensorList
        Trace Shapes:
         Param Sites:
        Sample Sites:
 persistent_beta dist |
                value |
persistent_death dist |
                value |
persistent_gamma dist |
                value |
   persistent_I0 dist |
                value |

RuntimeError: stack expects a non-empty TensorList
        Trace Shapes:
         Param Sites:
        Sample Sites:
 persistent_beta dist |
                value |
persistent_death dist |
                value |
persistent_gamma dist |
                value |
   persistent_I0 dist |
                value |