In [1]:
import pyciemss

In [16]:
start_time = 0.0
end_time = 40.0
logging_step_size = 1.0
num_samples = 1

model = "SIR_with_observable_namespace_collision.json"

result_preoptimize = pyciemss.sample(
    model,
    end_time,
    logging_step_size,
    num_samples,
    start_time = start_time,
    solver_method = "dopri5"
)

ERROR:root:
                ###############################

                There was an exception in pyciemss

                Error occured in function: sample

                Function docs :
    Load a model from a file, compile it into a probabilistic program, and sample from it.

    Args:
        model_path_or_json: Union[str, Dict]
            - A path to a AMR model file or JSON containing a model in AMR form.
        end_time: float
            - The end time of the sampled simulation.
        logging_step_size: float
            - The step size to use for logging the trajectory.
        num_samples: int
            - The number of samples to draw from the model.
        solver_method: str
            - The method to use for solving the ODE. See torchdiffeq's `odeint` method for more details.
            - If performance is incredibly slow, we suggest using `euler` to debug.
              If using `euler` results in faster simulation, the issue is likely that the model is stiff.
        solver_options: Dict[str, Any]
            - Options to pass to the solver (including atol and rtol).
              See torchdiffeq' `odeint` method for more details.
        start_time: float
            - The start time of the model. This is used to align the `start_state` from the
              AMR model with the simulation timepoints.
            - By default we set the `start_time` to be 0.
        inferred_parameters: Optional[pyro.nn.PyroModule]
            - A Pyro module that contains the inferred parameters of the model.
              This is typically the result of `calibrate`.
            - If not provided, we will use the default values from the AMR model.
        static_state_interventions: Dict[float, Dict[str, Intervention]]
            - A dictionary of static interventions to apply to the model.
            - Each key is the time at which the intervention is applied.
            - Each value is a dictionary of the form {state_variable_name: intervention_assignment}.
            - Note that the `intervention_assignment` can be any type supported by
              :func:`~chirho.interventional.ops.intervene`, including functions.
        static_parameter_interventions: Dict[float, Dict[str, Intervention]]
            - A dictionary of static interventions to apply to the model.
            - Each key is the time at which the intervention is applied.
            - Each value is a dictionary of the form {parameter_name: intervention_assignment}.
            - Note that the `intervention_assignment` can be any type supported by
              :func:`~chirho.interventional.ops.intervene`, including functions.
        dynamic_state_interventions: Dict[
                                        Callable[[torch.Tensor, Dict[str, torch.Tensor]], torch.Tensor],
                                        Dict[str, Intervention]
                                        ]
            - A dictionary of dynamic interventions to apply to the model.
            - Each key is a function that takes in the current state of the model and returns a tensor.
              When this function crosses 0, the dynamic intervention is applied.
            - Each value is a dictionary of the form {state_variable_name: intervention_assignment}.
            - Note that the `intervention_assignment` can be any type supported by
              :func:`~chirho.interventional.ops.intervene`, including functions.
        dynamic_parameter_interventions: Dict[
                                            Callable[[torch.Tensor, Dict[str, torch.Tensor]], torch.Tensor],
                                            Dict[str, Intervention]
                                            ]
            - A dictionary of dynamic interventions to apply to the model.
            - Each key is a function that takes in the current state of the model and returns a tensor.
              When this function crosses 0, the dynamic intervention is applied.
            - Each value is a dictionary of the form {parameter_name: intervention_assignment}.
            - Note that the `intervention_assignment` can be any type supported by
              :func:`~chirho.interventional.ops.intervene`, including functions.
        alpha: Union[List[float], float]
            - A (list of) risk preference parameter(s) for alpha-superquantile outputs in the results dictionary.
        qoi: Optional[Union[List[Callable[[Any], np.ndarray]],Callable[[Any], np.ndarray]]]
            - A (list of) callable function(s) defining the quantity of interest to optimize over.
            - If not provided, QoIs are assumed to be the value of all states and observables on the last day.

    Returns:
        result: Dict[str, Any]
            - Dictionary of outputs with following attributes:
                - data: The samples from the model as a pandas DataFrame.
                - unprocessed_result: Dictionary of outputs from the model.
                    - Each key is the name of a parameter or state variable in the model.
                    - Each value is a tensor of shape (num_samples, num_timepoints) for state variables
                    and (num_samples,) for parameters.
                - risk: Dictionary with each key as the name of a state with
                a dictionary of risk estimates for each state at the final timepoint.
                    - risk: alpha-superquantile risk estimate
                    Superquantiles can be intuitively thought of as a tail expectation, or an average
                    over a portion of worst-case outcomes. Given a distribution of a
                    quantity of interest (QoI), the superquantile at level \alpha\in[0, 1] is
                    the expected value of the largest 100(1 -\alpha)% realizations of the QoI.
                    - qoi: Samples of quantity of interest (value of the state at the final timepoint)
                - schema: Visualization. (If visual_options is truthy)


                ################################

Traceback (most recent call last):
  File "/Users/altu809/Projects/pyciemss/pyciemss/integration_utils/custom_decorators.py", line 10, in wrapped
    result = function(*args, **kwargs)
  File "/Users/altu809/Projects/pyciemss/pyciemss/interfaces.py", line 551, in sample
    samples = pyro.infer.Predictive(
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/pyro/infer/predictive.py", line 273, in forward
    return _predictive(
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/pyro/infer/predictive.py", line 78, in _predictive
    max_plate_nesting = _guess_max_plate_nesting(model, model_args, model_kwargs)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/pyro/infer/predictive.py", line 21, in _guess_max_plate_nesting
    model_trace = poutine.trace(model).get_trace(*args, **kwargs)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/pyro/poutine/trace_messenger.py", line 198, in get_trace
    self(*args, **kwargs)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/pyro/poutine/trace_messenger.py", line 174, in __call__
    ret = self.fn(*args, **kwargs)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
  File "/Users/altu809/Projects/pyciemss/pyciemss/interfaces.py", line 524, in wrapped_model
    full_trajectory = model(
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/pyro/nn/module.py", line 449, in __call__
    result = super().__call__(*args, **kwargs)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/altu809/Projects/pyciemss/pyciemss/compiled_dynamics.py", line 127, in forward
    simulate(self.deriv, self.initial_state(), start_time, end_time)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/pyro/poutine/runtime.py", line 281, in _fn
    apply_stack(msg)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/pyro/poutine/runtime.py", line 220, in apply_stack
    frame._postprocess_message(msg)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/pyro/poutine/messenger.py", line 168, in _postprocess_message
    return method(msg)
  File "/Users/altu809/Projects/pyciemss/pyciemss/compiled_dynamics.py", line 272, in _pyro_post_simulate
    self.lt._pyro_post_simulate(msg)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/chirho/dynamical/handlers/trajectory.py", line 67, in _pyro_post_simulate
    self._trajectory: State[T] = append(
  File "/Users/altu809/anaconda3/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/chirho/dynamical/internals/_utils.py", line 34, in _append_trajectory
    return type(traj1)(**{k: append(traj1[k], traj2[k]) for k in traj1.keys()})
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/chirho/dynamical/internals/_utils.py", line 34, in <dictcomp>
    return type(traj1)(**{k: append(traj1[k], traj2[k]) for k in traj1.keys()})
  File "/Users/altu809/anaconda3/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/chirho/dynamical/internals/_utils.py", line 42, in _append_tensor
    curr_v = curr_v.expand(*batch_shape, *curr_v.shape[-1:])
TypeError: expand() missing 1 required positional arguments: "size"

TypeError: expand() missing 1 required positional arguments: "size"

In [30]:
model = "SIR_with_observable.json" # has observable Rnot instead of R0

result_preoptimize = pyciemss.sample(
    model,
    end_time,
    logging_step_size,
    num_samples,
    start_time = start_time,
    solver_method = "dopri5"
)
display(result_preoptimize["data"])

ERROR:root:
                ###############################

                There was an exception in pyciemss

                Error occured in function: sample

                Function docs :
    Load a model from a file, compile it into a probabilistic program, and sample from it.

    Args:
        model_path_or_json: Union[str, Dict]
            - A path to a AMR model file or JSON containing a model in AMR form.
        end_time: float
            - The end time of the sampled simulation.
        logging_step_size: float
            - The step size to use for logging the trajectory.
        num_samples: int
            - The number of samples to draw from the model.
        solver_method: str
            - The method to use for solving the ODE. See torchdiffeq's `odeint` method for more details.
            - If performance is incredibly slow, we suggest using `euler` to debug.
              If using `euler` results in faster simulation, the issue is likely that the model is stiff.
        solver_options: Dict[str, Any]
            - Options to pass to the solver (including atol and rtol).
              See torchdiffeq' `odeint` method for more details.
        start_time: float
            - The start time of the model. This is used to align the `start_state` from the
              AMR model with the simulation timepoints.
            - By default we set the `start_time` to be 0.
        inferred_parameters: Optional[pyro.nn.PyroModule]
            - A Pyro module that contains the inferred parameters of the model.
              This is typically the result of `calibrate`.
            - If not provided, we will use the default values from the AMR model.
        static_state_interventions: Dict[float, Dict[str, Intervention]]
            - A dictionary of static interventions to apply to the model.
            - Each key is the time at which the intervention is applied.
            - Each value is a dictionary of the form {state_variable_name: intervention_assignment}.
            - Note that the `intervention_assignment` can be any type supported by
              :func:`~chirho.interventional.ops.intervene`, including functions.
        static_parameter_interventions: Dict[float, Dict[str, Intervention]]
            - A dictionary of static interventions to apply to the model.
            - Each key is the time at which the intervention is applied.
            - Each value is a dictionary of the form {parameter_name: intervention_assignment}.
            - Note that the `intervention_assignment` can be any type supported by
              :func:`~chirho.interventional.ops.intervene`, including functions.
        dynamic_state_interventions: Dict[
                                        Callable[[torch.Tensor, Dict[str, torch.Tensor]], torch.Tensor],
                                        Dict[str, Intervention]
                                        ]
            - A dictionary of dynamic interventions to apply to the model.
            - Each key is a function that takes in the current state of the model and returns a tensor.
              When this function crosses 0, the dynamic intervention is applied.
            - Each value is a dictionary of the form {state_variable_name: intervention_assignment}.
            - Note that the `intervention_assignment` can be any type supported by
              :func:`~chirho.interventional.ops.intervene`, including functions.
        dynamic_parameter_interventions: Dict[
                                            Callable[[torch.Tensor, Dict[str, torch.Tensor]], torch.Tensor],
                                            Dict[str, Intervention]
                                            ]
            - A dictionary of dynamic interventions to apply to the model.
            - Each key is a function that takes in the current state of the model and returns a tensor.
              When this function crosses 0, the dynamic intervention is applied.
            - Each value is a dictionary of the form {parameter_name: intervention_assignment}.
            - Note that the `intervention_assignment` can be any type supported by
              :func:`~chirho.interventional.ops.intervene`, including functions.
        alpha: Union[List[float], float]
            - A (list of) risk preference parameter(s) for alpha-superquantile outputs in the results dictionary.
        qoi: Optional[Union[List[Callable[[Any], np.ndarray]],Callable[[Any], np.ndarray]]]
            - A (list of) callable function(s) defining the quantity of interest to optimize over.
            - If not provided, QoIs are assumed to be the value of all states and observables on the last day.

    Returns:
        result: Dict[str, Any]
            - Dictionary of outputs with following attributes:
                - data: The samples from the model as a pandas DataFrame.
                - unprocessed_result: Dictionary of outputs from the model.
                    - Each key is the name of a parameter or state variable in the model.
                    - Each value is a tensor of shape (num_samples, num_timepoints) for state variables
                    and (num_samples,) for parameters.
                - risk: Dictionary with each key as the name of a state with
                a dictionary of risk estimates for each state at the final timepoint.
                    - risk: alpha-superquantile risk estimate
                    Superquantiles can be intuitively thought of as a tail expectation, or an average
                    over a portion of worst-case outcomes. Given a distribution of a
                    quantity of interest (QoI), the superquantile at level \alpha\in[0, 1] is
                    the expected value of the largest 100(1 -\alpha)% realizations of the QoI.
                    - qoi: Samples of quantity of interest (value of the state at the final timepoint)
                - schema: Visualization. (If visual_options is truthy)


                ################################

Traceback (most recent call last):
  File "/Users/altu809/Projects/pyciemss/pyciemss/integration_utils/custom_decorators.py", line 10, in wrapped
    result = function(*args, **kwargs)
  File "/Users/altu809/Projects/pyciemss/pyciemss/interfaces.py", line 551, in sample
    samples = pyro.infer.Predictive(
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/pyro/infer/predictive.py", line 273, in forward
    return _predictive(
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/pyro/infer/predictive.py", line 78, in _predictive
    max_plate_nesting = _guess_max_plate_nesting(model, model_args, model_kwargs)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/pyro/infer/predictive.py", line 21, in _guess_max_plate_nesting
    model_trace = poutine.trace(model).get_trace(*args, **kwargs)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/pyro/poutine/trace_messenger.py", line 198, in get_trace
    self(*args, **kwargs)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/pyro/poutine/trace_messenger.py", line 174, in __call__
    ret = self.fn(*args, **kwargs)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
  File "/Users/altu809/Projects/pyciemss/pyciemss/interfaces.py", line 524, in wrapped_model
    full_trajectory = model(
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/pyro/nn/module.py", line 449, in __call__
    result = super().__call__(*args, **kwargs)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/altu809/Projects/pyciemss/pyciemss/compiled_dynamics.py", line 127, in forward
    simulate(self.deriv, self.initial_state(), start_time, end_time)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/pyro/poutine/runtime.py", line 281, in _fn
    apply_stack(msg)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/pyro/poutine/runtime.py", line 220, in apply_stack
    frame._postprocess_message(msg)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/pyro/poutine/messenger.py", line 168, in _postprocess_message
    return method(msg)
  File "/Users/altu809/Projects/pyciemss/pyciemss/compiled_dynamics.py", line 272, in _pyro_post_simulate
    self.lt._pyro_post_simulate(msg)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/chirho/dynamical/handlers/trajectory.py", line 67, in _pyro_post_simulate
    self._trajectory: State[T] = append(
  File "/Users/altu809/anaconda3/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/chirho/dynamical/internals/_utils.py", line 34, in _append_trajectory
    return type(traj1)(**{k: append(traj1[k], traj2[k]) for k in traj1.keys()})
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/chirho/dynamical/internals/_utils.py", line 34, in <dictcomp>
    return type(traj1)(**{k: append(traj1[k], traj2[k]) for k in traj1.keys()})
  File "/Users/altu809/anaconda3/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Users/altu809/anaconda3/lib/python3.10/site-packages/chirho/dynamical/internals/_utils.py", line 42, in _append_tensor
    curr_v = curr_v.expand(*batch_shape, *curr_v.shape[-1:])
TypeError: expand() missing 1 required positional arguments: "size"

TypeError: expand() missing 1 required positional arguments: "size"

In [6]:
model = "SIR_without_observable.json"

result_preoptimize = pyciemss.sample(
    model,
    end_time,
    logging_step_size,
    num_samples,
    start_time = start_time,
    solver_method = "dopri5"
)
display(result_preoptimize["data"])

,timepoint_id,sample_id,timepoint_unknown,persistent_b_param,persistent_g_param,persistent_S0_param,persistent_I0_param,persistent_R0_param,S_state,I_state,R_state
0,0,0,0.0,0.2,0.06,0.9,0.1,0.0,0.900000,0.100000,0.000000
1,1,0,1.0,0.2,0.06,0.9,0.1,0.0,0.881089,0.112540,0.006371
2,2,0,2.0,0.2,0.06,0.9,0.1,0.0,0.860323,0.126151,0.013526
3,3,0,3.0,0.2,0.06,0.9,0.1,0.0,0.837674,0.140796,0.021530
4,4,0,4.0,0.2,0.06,0.9,0.1,0.0,0.813157,0.156402,0.030441
5,5,0,5.0,0.2,0.06,0.9,0.1,0.0,0.786830,0.172855,0.040315
6,6,0,6.0,0.2,0.06,0.9,0.1,0.0,0.758798,0.190004,0.051198
7,7,0,7.0,0.2,0.06,0.9,0.1,0.0,0.729221,0.207654,0.063125
8,8,0,8.0,0.2,0.06,0.9,0.1,0.0,0.698307,0.225573,0.076122
9,9,0,9.0,0.2,0.06,0.9,0.1,0.0,0.666305,0.243501,0.090194
10,10,0,10.0,0.2,0.06,0.9,0.1,0.0,0.633508,0.261155,0.105336
11,11,0,11.0,0.2,0.06,0.9,0.1,0.0,0.600236,0.278243,0.121522
12,12,0,12.0,0.2,0.06,0.9,0.1,0.0,0.566816,0.294476,0.138708
13,13,0,13.0,0.2,0.06,0.9,0.1,0.0,0.533579,0.309585,0.156836
14,14,0,14.0,0.2,0.06,0.9,0.1,0.0,0.500842,0.323326,0.175831
15,15,0,15.0,0.2,0.06,0.9,0.1,0.0,0.468896,0.335500,0.195604
16,16,0,16.0,0.2,0.06,0.9,0.1,0.0,0.437996,0.345949,0.216056
17,17,0,17.0,0.2,0.06,0.9,0.1,0.0,0.408350,0.354569,0.237081
18,18,0,18.0,0.2,0.06,0.9,0.1,0.0,0.380126,0.361306,0.258567
19,19,0,19.0,0.2,0.06,0.9,0.1,0.0,0.353445,0.366155,0.280400
20,20,0,20.0,0.2,0.06,0.9,0.1,0.0,0.328378,0.369153,0.302468
21,21,0,21.0,0.2,0.06,0.9,0.1,0.0,0.304961,0.370376,0.324663
22,22,0,22.0,0.2,0.06,0.9,0.1,0.0,0.283193,0.369927,0.346880
23,23,0,23.0,0.2,0.06,0.9,0.1,0.0,0.263043,0.367933,0.369023
24,24,0,24.0,0.2,0.06,0.9,0.1,0.0,0.244459,0.364537,0.391004
25,25,0,25.0,0.2,0.06,0.9,0.1,0.0,0.227372,0.359886,0.412743
26,26,0,26.0,0.2,0.06,0.9,0.1,0.0,0.211699,0.354132,0.434168
27,27,0,27.0,0.2,0.06,0.9,0.1,0.0,0.197353,0.347427,0.455220
28,28,0,28.0,0.2,0.06,0.9,0.1,0.0,0.184242,0.339915,0.475844
29,29,0,29.0,0.2,0.06,0.9,0.1,0.0,0.172272,0.331732,0.495996
30,30,0,30.0,0.2,0.06,0.9,0.1,0.0,0.161353,0.323007,0.515641
31,31,0,31.0,0.2,0.06,0.9,0.1,0.0,0.151396,0.313855,0.534749
32,32,0,32.0,0.2,0.06,0.9,0.1,0.0,0.142319,0.304384,0.553297
33,33,0,33.0,0.2,0.06,0.9,0.1,0.0,0.134043,0.294687,0.571270
34,34,0,34.0,0.2,0.06,0.9,0.1,0.0,0.126496,0.284848,0.588657
35,35,0,35.0,0.2,0.06,0.9,0.1,0.0,0.119609,0.274941,0.605450
36,36,0,36.0,0.2,0.06,0.9,0.1,0.0,0.113322,0.265029,0.621649
37,37,0,37.0,0.2,0.06,0.9,0.1,0.0,0.107577,0.255167,0.637255
38,38,0,38.0,0.2,0.06,0.9,0.1,0.0,0.102325,0.245403,0.652271
39,39,0,39.0,0.2,0.06,0.9,0.1,0.0,0.097518,0.235776,0.666706
40,40,0,40.0,0.2,0.06,0.9,0.1,0.0,0.093115,0.226317,0.680568

In [25]:
model = "SIR_with_param_in_obs.json"

result_preoptimize = pyciemss.sample(
    model,
    end_time,
    logging_step_size,
    num_samples,
    start_time = start_time,
    solver_method = "dopri5"
)
display(result_preoptimize["data"])

,timepoint_id,sample_id,timepoint_unknown,persistent_beta_param,persistent_gamma_param,S_state,I_state,R_state,incident_cases_observable_state,beta_param_observable_state
0,0,0,0.0,0.002893,0.07,9.990000e+02,1.000000,0.000000,2.890409e+00,0.041333
1,1,0,1.0,0.002893,0.07,9.830533e+02,16.558176,0.389333,4.709593e+01,0.041333
2,2,0,2.0,0.002893,0.07,7.753958e+02,218.472916,6.130233,4.901340e+02,0.041333
3,3,0,3.0,0.002893,0.07,1.751862e+02,782.694275,42.119122,3.967216e+02,0.041333
4,4,0,4.0,0.002893,0.07,1.445294e+01,883.066406,102.481384,3.692694e+01,0.041333
5,5,0,5.0,0.002893,0.07,1.194133e+00,835.997559,162.808243,2.888362e+00,0.041333
6,6,0,6.0,0.002893,0.07,1.152404e-01,780.507385,219.377243,2.602409e-01,0.041333
7,7,0,7.0,0.002893,0.07,1.301117e-02,727.837952,272.149017,2.739964e-02,0.041333
8,8,0,8.0,0.002893,0.07,1.702243e-03,678.643066,321.355560,3.342387e-03,0.041333
9,9,0,9.0,0.002893,0.07,2.555273e-04,632.763367,367.236389,4.678131e-04,0.041333
10,10,0,10.0,0.002893,0.07,4.360449e-05,589.984924,410.015045,7.443307e-05,0.041333
11,11,0,11.0,0.002893,0.07,8.385949e-06,550.097961,449.902039,1.334707e-05,0.041333
12,12,0,12.0,0.002893,0.07,1.802760e-06,512.908203,487.091644,2.675293e-06,0.041333
13,13,0,13.0,0.002893,0.07,4.300295e-07,478.232391,521.767517,5.950193e-07,0.041333
14,14,0,14.0,0.002893,0.07,1.130407e-07,445.901031,554.099304,1.458368e-07,0.041333
15,15,0,15.0,0.002893,0.07,3.259245e-08,415.755646,584.245178,3.920568e-08,0.041333
16,16,0,16.0,0.002893,0.07,1.016078e-08,387.647766,612.352356,1.139615e-08,0.041333
17,17,0,17.0,0.002893,0.07,3.422914e-09,361.440277,638.559570,3.579533e-09,0.041333
18,18,0,18.0,0.002893,0.07,1.360586e-09,337.004517,662.995056,1.326648e-09,0.041333
19,19,0,19.0,0.002893,0.07,4.824875e-10,314.221008,685.778931,4.386469e-10,0.041333
20,20,0,20.0,0.002893,0.07,2.467815e-10,292.977386,707.022888,2.091898e-10,0.041333
21,21,0,21.0,0.002893,0.07,1.251803e-10,273.170685,726.829285,9.893820e-11,0.041333
22,22,0,22.0,0.002893,0.07,5.866435e-11,254.702942,745.297546,4.323167e-11,0.041333
23,23,0,23.0,0.002893,0.07,3.147409e-11,237.483200,762.516785,2.162618e-11,0.041333
24,24,0,24.0,0.002893,0.07,1.603504e-11,221.427841,778.571960,1.027297e-11,0.041333
25,25,0,25.0,0.002893,0.07,8.944980e-12,206.457962,793.541992,5.343241e-12,0.041333
26,26,0,26.0,0.002893,0.07,4.997252e-12,192.500137,807.499695,2.783275e-12,0.041333
27,27,0,27.0,0.002893,0.07,2.946175e-12,179.486237,820.513062,1.529972e-12,0.041333
28,28,0,28.0,0.002893,0.07,1.785158e-12,167.351547,832.648499,8.643710e-13,0.041333
29,29,0,29.0,0.002893,0.07,1.120192e-12,156.037323,843.963135,5.057254e-13,0.041333
30,30,0,30.0,0.002893,0.07,7.254821e-13,145.488464,854.511475,3.053860e-13,0.041333
31,31,0,31.0,0.002893,0.07,4.830952e-13,135.652679,864.347351,1.896072e-13,0.041333
32,32,0,32.0,0.002893,0.07,3.310272e-13,126.481606,873.518250,1.211392e-13,0.041333
33,33,0,33.0,0.002893,0.07,2.324105e-13,117.930649,882.069275,7.930055e-14,0.041333
34,34,0,34.0,0.002893,0.07,1.672444e-13,109.957764,890.042175,5.320732e-14,0.041333
35,35,0,35.0,0.002893,0.07,1.229856e-13,102.523979,897.475952,3.648156e-14,0.041333
36,36,0,36.0,0.002893,0.07,9.236668e-14,95.592728,904.407410,2.554665e-14,0.041333
37,37,0,37.0,0.002893,0.07,7.071239e-14,89.130081,910.869812,1.823533e-14,0.041333
38,38,0,38.0,0.002893,0.07,5.512540e-14,83.104370,916.895691,1.325468e-14,0.041333
39,39,0,39.0,0.002893,0.07,4.370252e-14,77.485970,922.513916,9.797681e-15,0.041333
40,40,0,40.0,0.002893,0.07,3.519417e-14,72.247459,927.752258,7.356768e-15,0.041333