# This notebook shows how observables disappear in simulation for certain model formats, namely regnets and stock-and-flow.
See https://github.com/ciemss/pyciemss/issues/552

### Load dependencies

In [1]:
import os
import json
import pyciemss

from mira.sources.amr import model_from_url, model_from_json_file
from mira.modeling.amr.regnet import template_model_to_regnet_json
from mira.modeling.amr.stockflow import template_model_to_stockflow_json

### Select models

In [16]:
MODEL_PATH = "../../docs/source/"
# MODEL_PATH = "https://raw.githubusercontent.com/DARPA-ASKEM/simulation-integration/main/data/models/"

petri_model = os.path.join(MODEL_PATH, "SEIRHD_base_model01_petrinet.json")
regnet_model = os.path.join(MODEL_PATH, "LV_rabbits_wolves_model03_regnet.json")
stockflow_model = model1 = os.path.join(MODEL_PATH, "SEIRHD_stockflow.json")

### Set simulation parameters

In [17]:
start_time = 0.0
end_time = 50.0
logging_step_size = 10.0
num_samples = 10

In [ ]:
result1 = pyciemss.sample(model1, end_time, logging_step_size, num_samples, start_time=start_time)
display(result1['data'].head())

In [ ]:
result1 = pyciemss.sample(model3, end_time, logging_step_size, num_samples, start_time=start_time)
display(result1['data'].head())

In [ ]:
# Regnet
result1 = pyciemss.sample(model5, end_time, logging_step_size, num_samples, start_time=start_time)
display(result1['data'].head())

In [ ]:
# Petrinet
result1 = pyciemss.sample(model6, end_time, logging_step_size, num_samples, start_time=start_time)
display(result1['data'].head())

In [ ]:
result1 = pyciemss.sample(model7, end_time, logging_step_size, num_samples, start_time=start_time)
display(result1['data'].head())

### Load a petrinet model as a template model, and observe its observables

In [19]:
# template_model = model_from_url(petri_model)
template_model = model_from_json_file(petri_model)
print(type(template_model))
display(template_model.observables)

<class 'mira.metamodel.template_model.TemplateModel'>

{'infected': Observable(name='infected', display_name='infected', description=None, identifiers={}, context={}, units=None, expression=I),
 'exposed': Observable(name='exposed', display_name='exposed', description=None, identifiers={}, context={}, units=None, expression=E),
 'hospitalized': Observable(name='hospitalized', display_name='hospitalized', description=None, identifiers={}, context={}, units=None, expression=H),
 'dead': Observable(name='dead', display_name='dead', description=None, identifiers={}, context={}, units=None, expression=D)}

### Simulate the model and see that observables appear in results

In [20]:
result1 = pyciemss.sample(template_model, end_time, logging_step_size, num_samples, start_time=start_time)
display(result1['data'].head())

,timepoint_id,sample_id,timepoint_unknown,persistent_beta_param,persistent_gamma_param,persistent_hosp_param,persistent_death_hosp_param,persistent_I0_param,D_state,E_state,H_state,I_state,R_state,S_state,infected_observable_state,exposed_observable_state,hospitalized_observable_state,dead_observable_state
0,0,0,10.0,0.445759,0.361843,0.068394,0.045235,8.275579,0.117637,39.835739,2.349319,25.223797,69.906311,19339904.0,25.223797,39.835739,2.349319,0.117637
1,1,0,20.0,0.445759,0.361843,0.068394,0.045235,8.275579,0.391665,55.139179,3.673777,34.951435,176.246109,19339772.0,34.951435,55.139179,3.673777,0.391665
2,2,0,30.0,0.445759,0.361843,0.068394,0.045235,8.275579,0.787611,76.354599,5.144420,48.399723,323.862305,19339586.0,48.399723,76.354599,5.144420,0.787611
3,3,0,40.0,0.445759,0.361843,0.068394,0.045235,8.275579,1.338136,105.730980,7.131483,67.021202,528.322205,19339334.0,67.021202,105.730980,7.131483,1.338136
4,0,1,10.0,0.369915,0.479410,0.151017,0.031504,8.134604,0.175041,21.315516,4.173529,12.103995,60.079266,19339944.0,12.103995,21.315516,4.173529,0.175041

### Now, load a regnet model, which does have observables in the AMR, and see that they do not propagate to the template version

In [25]:
# template_model = model_from_url(regnet_model)
template_model = model_from_json_file(regnet_model)
display(template_model.observables)

{}

### Sample the regnet model, and see that no observables appear in the sample results
There should be an `R_observable_state`, and a `W_observable_state`

In [26]:
result1 = pyciemss.sample(regnet_model, end_time, logging_step_size, num_samples, start_time=start_time)
display(result1['data'].head())

,timepoint_id,sample_id,timepoint_unknown,persistent_alpha_param,persistent_gamma_param,persistent_beta_param,persistent_delta_param,persistent_R0_param,persistent_W0_param,Rabbits_state,Wolves_state
0,0,0,10.0,0.522750,1.944868,0.525069,1.942551,1.042346,1.018033,0.977152,0.930710
1,1,0,20.0,0.522750,1.944868,0.525069,1.942551,1.042346,1.018033,0.998878,1.078672
2,2,0,30.0,0.522750,1.944868,0.525069,1.942551,1.042346,1.018033,1.027521,0.933255
3,3,0,40.0,0.522750,1.944868,0.525069,1.942551,1.042346,1.018033,0.960310,1.011162
4,0,1,10.0,0.538991,1.956996,0.516302,1.961839,1.118141,1.078064,0.938851,0.855519

### Repeat for a stock-and-flow model: no observables appear in the template model

In [27]:
# template_model = model_from_url(stockflow_model)
template_model = model_from_json_file(stockflow_model)
display(template_model.observables)

{}

### Sample the stock-and-flow model, and see that no observables appear in the sample results
There should be an `infected_observable_state`, and a `hospitalized_observable_state`

In [28]:
result1 = pyciemss.sample(stockflow_model, end_time, logging_step_size, num_samples, start_time=start_time)
display(result1['data'].head())

,timepoint_id,sample_id,timepoint_unknown,persistent_p_cbeta_param,persistent_p_cdelta_param,persistent_p_cgamma_param,persistent_p_hosp_param,persistent_p_death_param,persistent_p_los_param,persistent_I0_param,D_state,E_state,H_state,I_state,R_state,S_state
0,0,0,10.0,0.40958,0.103848,0.179239,0.153911,0.066393,6.271647,5.774724,0.039851,10.737334,0.589953,4.718967,7.103147,977.810120
1,1,0,20.0,0.40958,0.103848,0.179239,0.153911,0.066393,6.271647,5.774724,0.126128,20.712158,1.096353,8.854118,18.243885,951.968140
2,2,0,30.0,0.40958,0.103848,0.179239,0.153911,0.066393,6.271647,5.774724,0.287867,37.805981,2.053585,16.439917,39.172348,905.239868
3,3,0,40.0,0.40958,0.103848,0.179239,0.153911,0.066393,6.271647,5.774724,0.585227,64.222305,3.697636,28.828770,77.012741,826.653320
4,0,1,10.0,0.42313,0.191597,0.192065,0.058121,0.088329,5.411371,4.811789,0.022454,8.788141,0.240951,6.008997,8.256191,977.682495